version: '3'

services:

  labs_lfi:
    build: "./LABS/lfi-labs/"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    ports:
      - 80:80
    hostname: lfi.hack.me
    networks:
      app_net:
        ipv4_address: 172.18.18.10

  labs_rh:
    build: "./LABS/lfi-labs/"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    ports:
      - 82:80
    hostname: rh.hack.me
    networks:
      rh_network:
        ipv4_address: 172.18.42.10



  labs_bruteforce:
    build: "./LABS/Lab-BruteForce-Linux"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    ports:
      - 22:22
    hostname: bruteforce.hack.me
    networks:
      app_net:
        ipv4_address: 172.18.18.11

  labs_heartblend:
    image: "hmlio/vaas-cve-2014-0160"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    ports:
      - 443:443
    hostname: heartblend.hack.me
    networks:
      app_net:
        ipv4_address: 172.18.18.12

  labs_juice-shop:
    image: "bkimminich/juice-shop"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    ports:
      - 3000:3000
    hostname: juice-shop.hack.me
    networks:
      app_net:
        ipv4_address: 172.18.18.13

  labs_dvwa:
    image: "m4n3dw0lf/docker-vulnerable-dvwa"
    ports:
      - 81:80
    links:
      - mysql
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    hostname: dvwa.hack.me
    networks:
      app_net:
        ipv4_address: 172.18.18.14

  labs_dsvw:
    image: "m4n3dw0lf/dsvw"
    ports:
      - 8081:8081
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    hostname: dsvw.hack.me
    networks:
      app_net:
        ipv4_address: 172.18.18.15

  labs_webgoat:
    image: "mrmendes/webgoat-docker"
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    hostname: webgoat.hack.me
    networks:
      app_net:
        ipv4_address: 172.18.18.16

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

#  labs_hackzon:
#    image: "m4n3dw0lf/hackazon"
#    links:
#      - mysql
#    depends_on:
#      - mysql
#    ports:
#      - 85:80
#    deploy:
#      resources:
#        limits:
#          cpus: '0.50'
#          memory: 50M
#        reservations:
#          cpus: '0.25'
#          memory: 20M
#    hostname: hackazon.hack.me
#    networks:
#      app_net:
#        ipv4_address: 172.18.18.104

#  labs_javavulnlab:
#    image: "m4n3dw0lf/javavulnerablelab"
#    ports:
#      - 84:8080
#    links:
#      - mysql
#    deploy:
#      resources:
#        limits:
#          cpus: '0.50'
#          memory: 50M
#        reservations:
#          cpus: '0.25'
#          memory: 20M
#    hostname: javavulnerablelab.hack.me
#    networks:
#      app_net:
#        ipv4_address: 172.18.18.17

  #labs_pure-ftpd:
  #  build: ./LABS/docker-pure-ftpd
    #image: httpd
  #  deploy:
  #    resources:
  #      limits:
  #        cpus: '0.50'
  #        memory: 50M
  #      reservations:
  #        cpus: '0.25'
  #        memory: 20M
  #  ports:
  #    - 21:21
  #    - 30000-30009:30000-30009
  #  networks:
  #    app_net:
  #      ipv4_address: 172.18.18.11



  # LABS CTFD
#  labs_ctfd:
#    image: "ctfd/ctfd"
#    deploy:
#      resources:
#        limits:
#          cpus: '0.50'
#          memory: 50M
#        reservations:
#          cpus: '0.25'
#          memory: 20M
#    ports:
#      - 80:8000
#    networks:
#      app_net:
#        ipv4_address: 172.18.18.2



networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.18.18.0/24
        #gateway: 172.18.18.1

  rh_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.18.42.0/24
        #gateway: 172.18.18.1
